// N2D2 auto-generated file.
// @ Thu Jul 11 13:28:08 2019

#include "network.h"

//#define TIME_ANALYSIS
//#define DATA_DYN_ANALYSIS
//#define ACC_DYN_ANALYSIS
#define ACC_DYN_REPORT CHW

static DATA_T conv1_data[CONV1_NB_OUTPUTS][CONV1_OUTPUTS_HEIGHT][CONV1_OUTPUTS_WIDTH];
static DATA_T conv2_data[CONV2_NB_OUTPUTS][CONV2_OUTPUTS_HEIGHT][CONV2_OUTPUTS_WIDTH];
static DATA_T fc1_data[FC1_NB_OUTPUTS];
static DATA_T fc2_data[FC2_NB_OUTPUTS];
DATA_T output_data[NB_OUTPUTS*OUTPUTS_HEIGHT*OUTPUTS_WIDTH]; 
static DATA_T output_spatial_data[NB_OUTPUTS][OUTPUTS_HEIGHT][OUTPUTS_WIDTH]; 
/************************************LAYER (1)***/
CONVCELL_UPROPAGATE(conv1, CONV1_NB_CHANNELS, CONV1_CHANNELS_HEIGHT, CONV1_CHANNELS_WIDTH, CONV1_NB_OUTPUTS, CONV1_OUTPUTS_HEIGHT, CONV1_OUTPUTS_WIDTH, CONV1_NB_KERNELS, CONV1_KERNEL_HEIGHT, CONV1_KERNEL_WIDTH)
/************************************LAYER (2)***/
CONVCELL_UPROPAGATE_COMPACT(conv2, CONV2_NB_CHANNELS, CONV2_CHANNELS_HEIGHT, CONV2_CHANNELS_WIDTH, CONV2_NB_OUTPUTS, CONV2_OUTPUTS_HEIGHT, CONV2_OUTPUTS_WIDTH, CONV2_NB_KERNELS, CONV2_KERNEL_HEIGHT, CONV2_KERNEL_WIDTH)
/************************************LAYER (3)***/
FCCELL_UPROPAGATE_2D(fc1, CONV2_NB_OUTPUTS, CONV2_OUTPUTS_HEIGHT, CONV2_OUTPUTS_WIDTH, FC1_NB_OUTPUTS, FC1_NB_CHANNELS, FC1_NB_WEIGHTS)
/************************************LAYER (4)***/
FCCELL_UPROPAGATE(fc2, FC2_NB_CHANNELS, FC2_NB_OUTPUTS, FC2_NB_WEIGHTS)
/************************************LAYER (5)***/
